# Generated by Django 4.1 on 2022-08-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_quantity_xomashyo_kod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WareHouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Xomashyo',
            new_name='MaterialModel',
        ),
        migrations.RenameModel(
            old_name='Mahsulot',
            new_name='ProductModel',
        ),
        migrations.DeleteModel(
            name='MahXom',
        ),
        migrations.AddField(
            model_name='warehousemodel',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productmodel'),
        ),
        migrations.AddField(
            model_name='productmaterialsmodel',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kerak', to='main.materialmodel'),
        ),
        migrations.AddField(
            model_name='productmaterialsmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productmodel'),
        ),
    ]
