# Generated by Django 4.1 on 2022-08-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productmaterialsmodel_warehousemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousemodel',
            name='part_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
