# Generated by Django 4.1 on 2022-08-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_warehousemodel_part_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousemodel',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.materialmodel'),
        ),
    ]
