# Generated by Django 4.1 on 2022-08-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_warehousemodel_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousemodel',
            name='part_id',
        ),
    ]
