# Generated by Django 4.1 on 2022-08-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_warehousemodel_part_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousemodel',
            name='part_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
